### ISSUE TITLE
OBD2 pinouts in the readme incorrect

### ISSUE THREAD

**Issue by alierhan** [rhysmorgan134/JaguarXf_CAN#2]
In the readme pinouts specified as pin 3=CAN-H and pin 11=CAN-L

Standard pinout is pin6=CAN-H and pin 16=CAN-L
![OBD2-Connector-Pinout](https://user-images.githubusercontent.com/43734541/78846852-7c52e080-7a50-11ea-8185-632d1607be03.png)

**Comment by rhysmorgan134** [comment]
For the program to work, you need to be onto the medium speed can bus. This is found on pins 3 and 11, however, this is jaguar specific and may change for other manufacturers. I will put the fact its for medium speed in the readme to make this clearer.

**Comment by alierhan** [comment]
> For the program to work, you need to be onto the medium speed can bus. This is found on pins 3 and 11, however, this is jaguar specific and may change for other manufacturers. I will put the fact its for medium speed in the readme to make this clearer.

Cheers mate
