### ISSUE TITLE
OBD2 pins connections

### ISSUE THREAD

**Issue by alierhan** [rhysmorgan134/JaguarXf_CAN#6]
In the readme pinouts specified as pin 3=CAN-H and pin 11=CAN-L

Standard pinout is pin6=CAN-H and pin 16=CAN-L
![OBD2-Connector-Pinout](https://user-images.githubusercontent.com/43734541/78846852-7c52e080-7a50-11ea-8185-632d1607be03.png)

**Comment by rhysmorgan134** [comment]
Pins for medium speed are 3 and 11, as shown here
https://github.com/rhysmorgan134/JaguarXf_CAN/issues/3#issuecomment-611297092
